name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write    # Add this permissions block      

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Run tests
        run: go test ./...

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Publish Go Module
        run: |
          git config --global user.name "Andrzej Witkowski"
          git config --global user.email "andrzej.witkowski@gmail.com"
          git tag -a ${{ github.ref }} -m "Release ${{ github.ref }}"
          git push origin ${{ github.ref }}